name: smart_task_manager
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.2
  flutter_launcher_icons: ^0.14.1
  freezed: ^3.2.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

  # Uncomment to add custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
